FROM openjdk:11.0.15
ARG SERVER_PORT
ENV SERVER_PORT=$SERVER_PORT
ARG KAFKA_BOOTSTRAP_SERVER_HOST
ENV KAFKA_BOOTSTRAP_SERVER_HOST=$KAFKA_BOOTSTRAP_SERVER_HOST
ARG KAFKA_BOOTSTRAP_SERVER_PORT
ENV KAFKA_BOOTSTRAP_SERVER_PORT=$KAFKA_BOOTSTRAP_SERVER_PORT
ARG KAFKA_CONSUMER_GROUP
ENV KAFKA_CONSUMER_GROUP=$KAFKA_CONSUMER_GROUP
ARG KAFKA_TOPIC_NAME
ENV KAFKA_TOPIC_NAME=$KAFKA_TOPIC_NAME
ARG MAIL_USERNAME
ENV MAIL_USERNAME=$MAIL_USERNAME
ARG MAIL_PASSWORD
ENV MAIL_PASSWORD=$MAIL_PASSWORD
ARG MAIL_HOST
ENV MAIL_HOST=$MAIL_HOST
ARG EMAIL_FROM
ENV EMAIL_FROM=$EMAIL_FROM
COPY . ./app

WORKDIR ./app
RUN chmod +x gradlew && ./gradlew build
WORKDIR ./build/libs/
ENTRYPOINT ["java", "-jar", "email-processor-0.0.1-SNAPSHOT.jar"]